version: 2
jobs:
    deploy_dev:
        docker:
            - image: circleci/openjdk:buster-node-browsers-legacy
        steps:
            - checkout
            - run:
                  name: Install package
                  command: yarn
            - run:
                  name: Make .env
                  command: |
                      echo API_KEY="${API_KEY}" > ./.env
                      echo AUTH_DOMAIN="${AUTH_DOMAIN}" >> ./.env
                      echo DATABASE_URL="${DATABASE_URL}" >> ./.env
                      echo PROJECT_ID="${PROJECT_ID}" >> ./.env
                      echo STORAGE_BUCKET="${STORAGE_BUCKET}" >> ./.env
                      echo MESSAGING_SENDER_ID="${MESSAGING_SENDER_ID}" >> ./.env
                      echo APP_ID="${APP_ID}" >> ./.env
                      echo ALGOLIA_APPLICATION_ID="${ALGOLIA_APPLICATION_ID}" >> ./.env
                      echo ALGOLIA_SEARCH_ONLY_API="${ALGOLIA_SEARCH_ONLY_API}" >> ./.env
                      echo ALGOLIA_INDEX_ACCOUNT="${ALGOLIA_INDEX_ACCOUNT}" >> ./.env
                      echo ALGOLIA_INDEX_POST="${ALGOLIA_INDEX_POST}" >> ./.env
            - run:
                  name: Testing security rules with JEST.
                  command: yarn test:jest
            - run:
                  name: Deploy security rules
                  command: ./node_modules/.bin/firebase deploy --only firestore:rules --token=$FIREBASE_TOKEN
            - run:
                  name: yarn build
                  command: yarn build
            - run:
                  name: deploy to Firebase Hosting
                  command: ./node_modules/.bin/firebase deploy --only hosting --token=$FIREBASE_TOKEN

workflows:
    version: 2
    deploy_dev:
        jobs:
            - deploy_dev:
                  filters:
                      branches:
                          only: develop
