version: 2
jobs:
    deploy_dev:
        docker:
            - image: circleci/node:12.15
        steps:
            - checkout
            - run:
                  name: Install package
                  command: yarn
            - run:
                  name: Make .env
                  command: |
                      echo API_KEY="${API_KEY}" > ./.env
                      echo AUTH_DOMAIN="${AUTH_DOMAIN}" >> ./.env
                      echo DATABASE_URL="${DATABASE_URL}" >> ./.env
                      echo PROJECT_ID="${PROJECT_ID}" >> ./.env
                      echo STORAGE_BUCKET="${STORAGE_BUCKET}" >> ./.env
                      echo MESSAGING_SENDER_ID="${MESSAGING_SENDER_ID}" >> ./.env
                      echo APP_ID="${APP_ID}" >> ./.env
            - run:
                  name: yarn build
                  command: yarn build
            - run:
                  name: deploy to Firebase Hosting
                  command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
    version: 2
    deploy_dev:
        jobs:
            - deploy_dev:
                  filters:
                      branches:
                          only: develop
